runtime: python27
api_version: 1
threadsafe: true

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^karma


handlers:
- url: /
  static_files: dist/tide-walker/index.html
  upload: dist/tide-walker/index.html

- url: /
  static_dir: dist/tide-walker

# OTHER WAY OF DOING IT FROM WORK PROJECTS
# - handlers:
# # Routing for bundles to serve directly
# - url: /((?:inline|main|polyfills|styles|runtime|vendor|scripts|5)\.[a-z0-9]+\.js)
#   secure: always
#   redirect_http_response_code: 301
#   static_files: dist/\1
#   upload: dist/.*

# # Routing for a prod styles.bundle.css to serve directly
# - url: /(styles\.[a-z0-9]+\.css)
#   secure: always
#   redirect_http_response_code: 301
#   static_files: dist/\1
#   upload: dist/.*

# # Routing for typedoc, assets and favicon.ico to serve directly
# - url: /((?:assets|docs)/.*|favicon\.ico|.*\.jpg|.*\.woff)
#   secure: always
#   redirect_http_response_code: 301
#   static_files: dist/\1
#   upload: dist/.*

# # Any other requests are routed to index.html for angular to handle so we don't need hash URLs
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   static_files: dist/index.html
#   upload: dist/index\.html
#   http_headers:
#     Strict-Transport-Security: max-age=31536000; includeSubDomains
#     X-Frame-Options: DENY